### ISSUE TITLE
Failing to generate Unique UIDs

### ISSUE THREAD

**Issue by uGiFarukh** [RobTillaart/UUID#8]
Recently I am experimenting with UUID generation on Arduino framework esp32. I came across this repo and tried using it. But it seems like this library is unable to produce UUIDs and always producing the same UUID when I am using the code show below:

```cpp
UUID uuid;
char *cNewUUID = (char *)malloc(37);
uuid.generate();
strcpy(cNewUUID, uuid.toCharArray());
```

Is there something I am particularly doing wrong or missing? Please help me out. Thank you.

**Comment by RobTillaart** [comment]
Thanks for the issue, I will dive into it asap

**Comment by RobTillaart** [comment]
The UUID's are generated by means of a (pseudo) random generator. 
When the random generator is not seeded randomly, it will generate the same sequence over and over.

**Comment by RobTillaart** [comment]
You should use the **seed(uint32_t s1, uint32_t s2)** function to inject two random uint32_t numbers

Or you can path line 34 to use the build in random generator of the ESP32

**Comment by RobTillaart** [comment]
Or combine those two, use the random generator of the ESP32 to generate the two seeds. (think this is best)

The use of a repeatable UUID's makes it possible to test / replay the generation.

**Comment by RobTillaart** [comment]
(edited your question to show syntax highlighting for readability)

**Comment by uGiFarukh** [comment]
> Or combine those two, use the random generator of the ESP32 to generate the two seeds.
> 
> The use of a repeatable UUID's makes it possible to test / replay the generation.

I would like to only use software RNG because my codebase needs to be portable. So, I cannot be using hardware RNG. I will probably have to generate a long uint32_t random number on every startup and then use that number to generate the UUID. If I do that, am I guaranteed with have an UUID which is universally unique?

**Comment by RobTillaart** [comment]
> am I guaranteed with have an UUID which is universally unique?

No, as the UUID is 132 bit so there only exist 2^132 unique UUID's, so by definition they are not universally unique.

You should find a way to extract entropy (randomness) from the environment. This can be a floating ADC, time between events at startup, a CRC from a part of memory and combine those. Extracting entropy is more difficult than you think. E.g. if you ask 100 persons to type some random digits these will seldom be random distributed. Better measure the time in micros() between the keypresses.

**Comment by RobTillaart** [comment]
If your entropy gathering is good than there is only a very small chance that you will get the same sequence.
Another hint: use an Real Time Clock, as time is not random in itself but date and time are pretty often different.
Do not forget to measure the time between the time of the first read and the moment the RTC jumps to the next second.
If you measure that in millis() you have some extra randomness.

**Comment by RobTillaart** [comment]
If your application is on the internet, you can get random numbers from https://www.random.org/ 
You only need to seed the UUID lib with two real random numbers and the PRNG does the rest.

**Comment by RobTillaart** [comment]
If you are using ESP32 can try this code (it will be a next release example).
It uses 2 random numbers (from a billion) to seed the Marsaglia PRNG. 
So it uses 1 of the approximately 10^18 start positions, not too bad.

```cpp
//
//    FILE: UUID_random_ESP32.ino
//  AUTHOR: Rob Tillaart
// PURPOSE: demo

#include "Arduino.h"
#include "UUID.h"

UUID uuid;

uint32_t start, stop, randomtime;

void setup()
{
  Serial.begin(115200);
  while (!Serial);

  Serial.println();
  Serial.println("UUID_test.ino");
  Serial.print("UUID_LIB_VERSION: ");
  Serial.println(UUID_LIB_VERSION);

  uint32_t seed1 = random(999999999);
  uint32_t seed2 = random(999999999);
  Serial.println(seed1, HEX);
  Serial.println(seed2, HEX);

  start = micros();
  uuid.seed(seed1, seed2);
  stop = micros();

  Serial.print("  seed time: ");
  Serial.println(stop - start);
  delay(100);

  start = micros();
  uuid.generate();
  stop = micros();

  Serial.print("   generate: ");
  Serial.println(stop - start);
  delay(100);

  start = micros();
  uuid.toCharArray();
  stop = micros();

  Serial.print("toCharArray: ");
  Serial.println(stop - start);
  delay(100);

  Serial.print("UUID: ");
  Serial.println(uuid);
}

void loop()
{
  uuid.generate();
  Serial.print("UUID: ");
  Serial.println(uuid);
  delay(1000);
}

//  -- END OF FILE --
```

**Comment by RobTillaart** [comment]
Added the example in the new 0.1.5 release.

@uGiFarukh 
Is your problem solved?

**Comment by uGiFarukh** [comment]
> Added the example in the new 0.1.5 release.
> 
> @uGiFarukh Is your problem solved?

I will update this issue after testing. Couldn't get to testing the new method you showed, yet.

**Comment by uGiFarukh** [comment]
@RobTillaart problem fixed. I used the random() function to seed the PRNG. Thanks a lot for the help. Closing the issue.
